### PR TITLE
MeetUp

### PR DESCRIPTION
**Pull request by ahluwaliatikant**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [ ] Extension 
- [x] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
- [x]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Review by sudhanshutiwari264 — COMMENTED** [review]
@ahluwaliatikant loved your work! :+1:  

it would be great if you can add audio to the demo video!
fantastic work @ahluwaliatikant  :clinking_glasses:

**Comment by ahluwaliatikant** [comment]
Thanks @sudhanshutiwari264 🙈! Will try to add a voiceover to the video .

**Comment by archithdwij** [comment]
@ahluwaliatikant This is fantastic work 👏 I love the interface, the link generation and addition of participants all in one place. Can we add links similar to generate google meet link? So in case if a company meeting wants to happen in zoom or teams or skype, can we do that as well? We will have choices and people may choose any one. Yeah?

**Review by theAdityaNVS — CHANGES_REQUESTED** [review]
Nice work on the UI and the Design language. 👍

**Comment by ahluwaliatikant** [comment]
Thank you @theAdityaNVS and @archithdwij !
@archithdwij Yes, integrating Zoom, Teams etc. is a great idea.
But the Flutter plugins are not available for Teams and Skype. As for Zoom, a plugin is available but it currently does not support scheduling future meetings. It only supports starting or joining an instant meeting ( only if the user logs in using email and password, not through Google/Facebook). 
So, adding partial features for Zoom would affect the User Experience. But I would definitely keep a watch on the same and integrate it as and when the plugin supports those features.

**Comment by archithdwij** [comment]
@ahluwaliatikant Alright then! In that case, can we just add a nice button or something that redirects to the app? Let me know if this is possible.

**Review by jainaayush01 — APPROVED** [review]
LGTM
kindly take a look at @archithdwij 's suggestions and get back to us asap.

**Comment by ahluwaliatikant** [comment]
Hey @jainaayush01 
Thanks for the review. I would look into the available Zoom API/integrations possible and add whatever would be feasible accordingly.

**Comment by ahluwaliatikant** [comment]
@archithdwij @jainaayush01 
I implemented in this way-
During creation of event user can either select generate Google meet link or use another app.
In the all meets screen if the user click on join now then:
1. If Generate Google meet was chosen while creating that event then the meeting will be automatically opened in GoogleMeet.
2. If Use Another app was chosen then the user will be directed to a screen where he is asked to choose one app to continue. If the chosen app is installed on the device the app will be opened otherwise user will be directed to play store.

I have also attached a short video showing it in practice.

https://user-images.githubusercontent.com/52076751/125158768-e052e000-e190-11eb-9438-b8aa7fc8d39b.mp4

**Comment by jainaayush01** [comment]
Hey, you haven't pushed the changes yet...

**Comment by ahluwaliatikant** [comment]
@jainaayush01 Ok will just push the changes. Was thinking I'll push them once the above solution is approved.

**Comment by ahluwaliatikant** [comment]
Hey @archithdwij @jainaayush01 , Please review the changes.

**Comment by ahluwaliatikant** [comment]
@archithdwij @jainaayush01 @theAdityaNVS  Hey, can you please review the changes and merge the PR so that I can submit the project.

**Review by theAdityaNVS — APPROVED** [review]
Looks good !! 👍

**Comment by archithdwij** [comment]
@all-contributors Please add @ahluwaliatikant for code, design, infra, idea

**Review by jainaayush01 — COMMENTED** [review]
Congratulations @ahluwaliatikant  for getting your PR merged 🥳
Kudos for the great work. 
We are waiting for your blog

**Comment by sudhanshutiwari264** [comment]
@ahluwaliatikant I appreciate your contribution and dedication.

**Comment by ahluwaliatikant** [comment]
@sudhanshutiwari264 @jainaayush01  Thanks a lot.

**Pull request merged**
